### ISSUE TITLE
大佬，这是字体文件坏了还是什么原因

### ISSUE THREAD

**Issue by Fahaxikiii** [SonderXiaoming/login_bonus#3]
[2022-07-29 02:25:00,652 nonebot] ERROR: Failed to import "hoshino.modules.login_bonus.base", error: cannot open resource
[2022-07-29 02:25:00,652 nonebot] ERROR: cannot open resource
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin.py", line 253, in load_plugin
    module = importlib.import_module(module_path)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/www/wwwroot/HoshinoBot/hoshino/modules/login_bonus/__init__.py", line 20, in <module>
    font = ImageFont.truetype('arial.ttf', 16)
  File "/usr/local/lib/python3.8/dist-packages/PIL/ImageFont.py", line 878, in truetype
    return freetype(font)
  File "/usr/local/lib/python3.8/dist-packages/PIL/ImageFont.py", line 875, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "/usr/local/lib/python3.8/dist-packages/PIL/ImageFont.py", line 226, in __init__
    self.font = core.getfont(
OSError: cannot open resource

**Comment by SonderXiaoming** [comment]
好像是你没有缺了自带的字体文件，Linux？如果你对字体没追求的话可以使用默认字体或者安装arial.ttf字体

**Comment by SonderXiaoming** [comment]
第20行改为font = ImageFont.load_default()，改成默认字体

**Comment by SonderXiaoming** [comment]
https://github.com/JotJunior/PHP-Boleto-ZF2/blob/master/public/assets/fonts/arial.ttf
安装arial.ttf字体

**Comment by Fahaxikiii** [comment]
> 第20行改为font = ImageFont.load_default()，改成默认字体

好的，谢谢！

**Comment by Fahaxikiii** [comment]
> https://github.com/JotJunior/PHP-Boleto-ZF2/blob/master/public/assets/fonts/arial.ttf 安装arial.ttf字体

好的

**Comment by kcn3388** [comment]
> https://github.com/JotJunior/PHP-Boleto-ZF2/blob/master/public/assets/fonts/arial.ttf 安装arial.ttf字体

文件路径如果不加prefix，直接``./*ttf``的话Windows和Linux的语法规则好像不一样的，最好是用``os.path``或者``config.RES_DIR``作为prefix，再指向字体文件，这样子跨平台也不会出问题

**Comment by SonderXiaoming** [comment]
> > https://github.com/JotJunior/PHP-Boleto-ZF2/blob/master/public/assets/fonts/arial.ttf 安装arial.ttf字体
> 
> 文件路径如果不加prefix，直接`./*ttf`的话Windows和Linux的语法规则好像不一样的，最好是用`os.path`或者`config.RES_DIR`作为prefix，再指向字体文件，这样子跨平台也不会出问题

应该将字体封装好的，我以为都有这个字体

**Comment by SonderXiaoming** [comment]
现在字体已经内置
